package types

import "time"

// ExtendedIntegration extends the base Integration type with additional fields
// from the OpsRamp API
type ExtendedIntegration struct {
	Integration
	DisplayName     string         `json:"displayName"`
	App             string         `json:"app"`
	Version         string         `json:"version"`
	Category        string         `json:"category"`
	State           string         `json:"state"`
	InstalledBy     string         `json:"installedBy"`
	InstalledTime   string         `json:"installedTime"`
	ModifiedBy      string         `json:"modifiedBy"`
	ModifiedTime    string         `json:"modifiedTime"`
	UpdateAvailable bool           `json:"updateAvailable"`
	InboundConfig   *InboundConfig `json:"inboundConfig,omitempty"`
	Profile         *Profile       `json:"profile,omitempty"`
}

// InboundConfig represents the inbound configuration of an integration
type InboundConfig struct {
	Authentication *Authentication `json:"authentication,omitempty"`
}

// Authentication represents the authentication configuration of an integration
type Authentication struct {
	AuthType    string       `json:"authType"`
	APIKeyPairs []APIKeyPair `json:"apiKeyPairs,omitempty"`
}

// APIKeyPair represents an API key pair
type APIKeyPair struct {
	Key string `json:"key"`
}

// Profile represents the profile of an integration
type Profile struct {
	ID                     int    `json:"id"`
	Name                   string `json:"name"`
	Status                 string `json:"status"`
	Registered             bool   `json:"registered"`
	UUID                   string `json:"uuId"`
	ConnectedStatus        int    `json:"connectedStatus"`
	MonitoredMetricsCount  int    `json:"monitoredMetricsCount"`
	AssignedTemplatesCount int    `json:"assignedTemplatesCount"`
}

// DetailedIntegration represents a detailed view of an OpsRamp integration
// This is used for the Get operation to show more details
type DetailedIntegration struct {
	ExtendedIntegration
	Resources        []IntegrationResource `json:"resources,omitempty"`
	Metrics          []Metric              `json:"metrics,omitempty"`
	Alerts           []Alert               `json:"alerts,omitempty"`
	LastDiscoveryRun *DiscoveryRunInfo     `json:"lastDiscoveryRun,omitempty"`
}

// IntegrationResource represents a resource discovered by an integration
type IntegrationResource struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	Status       string    `json:"status"`
	DiscoveredAt time.Time `json:"discoveredAt"`
}

// Metric represents a metric collected by an integration
type Metric struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Unit        string `json:"unit"`
	Type        string `json:"type"`
}

// Alert represents an alert generated by an integration
type Alert struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Severity    string    `json:"severity"`
	Status      string    `json:"status"`
	CreatedTime time.Time `json:"createdTime"`
}

// DiscoveryRunInfo represents information about the last discovery run
type DiscoveryRunInfo struct {
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
	Status    string    `json:"status"`
	Resources int       `json:"resourcesDiscovered"`
}
